import {
  MessageSquare,
  Clock,
  MessageCircleQuestion,
  GitBranch,
  Flag,
  Zap,
  Image,
  Mic,
  FileText,
  Video,
  Link as LinkIcon,
  MousePointerClick,
  MoveRight,
  Tag,
  Tags,
  UserCog,
  UserSquare,
  Bot,
  BotOff,
  Variable,
  Bell,
  PlayCircle,
  Sparkles,
  type LucideIcon,
} from 'lucide-vue-next'

export type NodeCatalogEntry = {
  type: string
  label: string
  description: string
  icon: LucideIcon
  color: string
  category: 'trigger' | 'action' | 'logic' | 'flow' | 'lead' | 'ai'
  defaultConfig: Record<string, unknown>
}

export const NODE_CATALOG: NodeCatalogEntry[] = [
  {
    type: 'trigger',
    label: 'Gatilho',
    description: 'Ponto de entrada do fluxo',
    icon: Zap,
    color: 'bg-amber-500',
    category: 'trigger',
    defaultConfig: {},
  },
  {
    type: 'send_text',
    label: 'Enviar mensagem',
    description: 'Texto para o lead',
    icon: MessageSquare,
    color: 'bg-emerald-500',
    category: 'action',
    defaultConfig: { text: '', delay_ms: null },
  },
  {
    type: 'send_image',
    label: 'Enviar imagem',
    description: 'Envia imagem por URL',
    icon: Image,
    color: 'bg-emerald-500',
    category: 'action',
    defaultConfig: { file_url: '', caption: '', file_name: '' },
  },
  {
    type: 'send_audio',
    label: 'Enviar áudio',
    description: 'Envia áudio por URL',
    icon: Mic,
    color: 'bg-emerald-500',
    category: 'action',
    defaultConfig: { file_url: '', file_name: '' },
  },
  {
    type: 'send_document',
    label: 'Enviar documento',
    description: 'Envia arquivo por URL',
    icon: FileText,
    color: 'bg-emerald-500',
    category: 'action',
    defaultConfig: { file_url: '', caption: '', file_name: '' },
  },
  {
    type: 'send_video',
    label: 'Enviar vídeo',
    description: 'Envia vídeo por URL',
    icon: Video,
    color: 'bg-emerald-500',
    category: 'action',
    defaultConfig: { file_url: '', caption: '', file_name: '' },
  },
  {
    type: 'send_link',
    label: 'Enviar link',
    description: 'Envia URL com preview',
    icon: LinkIcon,
    color: 'bg-emerald-500',
    category: 'action',
    defaultConfig: { url: '', text: '' },
  },
  {
    type: 'send_buttons',
    label: 'Enviar botões',
    description: 'Menu com até 3 botões',
    icon: MousePointerClick,
    color: 'bg-emerald-500',
    category: 'action',
    defaultConfig: { text: '', footer_text: '', buttons: [] },
  },
  {
    type: 'wait_delay',
    label: 'Aguardar',
    description: 'Pausa por N segundos',
    icon: Clock,
    color: 'bg-sky-500',
    category: 'action',
    defaultConfig: { seconds: 5 },
  },
  {
    type: 'wait_reply',
    label: 'Aguardar resposta',
    description: 'Espera próxima msg do lead',
    icon: MessageCircleQuestion,
    color: 'bg-violet-500',
    category: 'action',
    defaultConfig: { variable: 'reply', timeout_seconds: 86400 },
  },
  {
    type: 'condition',
    label: 'Condição',
    description: 'Ramificação por regras',
    icon: GitBranch,
    color: 'bg-orange-500',
    category: 'logic',
    defaultConfig: { branches: [], else: null },
  },
  {
    type: 'move_column',
    label: 'Mover coluna',
    description: 'Muda coluna do lead',
    icon: MoveRight,
    color: 'bg-blue-500',
    category: 'lead',
    defaultConfig: { coluna_id: '' },
  },
  {
    type: 'tag_add',
    label: 'Adicionar tag',
    description: 'Adiciona tag ao lead',
    icon: Tag,
    color: 'bg-blue-500',
    category: 'lead',
    defaultConfig: { tag: '' },
  },
  {
    type: 'tag_remove',
    label: 'Remover tag',
    description: 'Remove tag do lead',
    icon: Tags,
    color: 'bg-blue-500',
    category: 'lead',
    defaultConfig: { tag: '' },
  },
  {
    type: 'assign_user',
    label: 'Atribuir usuário',
    description: 'Define responsável',
    icon: UserCog,
    color: 'bg-blue-500',
    category: 'lead',
    defaultConfig: { user_id: '' },
  },
  {
    type: 'update_lead_fields',
    label: 'Atualizar lead',
    description: 'Atualiza campos do lead',
    icon: UserSquare,
    color: 'bg-blue-500',
    category: 'lead',
    defaultConfig: { fields: {} },
  },
  {
    type: 'set_ai_active',
    label: 'IA lead on/off',
    description: 'Ativa/desativa IA no lead',
    icon: Bot,
    color: 'bg-purple-500',
    category: 'ai',
    defaultConfig: { ativa: true },
  },
  {
    type: 'pause_ai_conversation',
    label: 'Pausar IA conversa',
    description: 'Pausa IA na conversa',
    icon: BotOff,
    color: 'bg-purple-500',
    category: 'ai',
    defaultConfig: { paused: true },
  },
  {
    type: 'invoke_agent',
    label: 'Invocar agente',
    description: 'Chama agente de IA agora',
    icon: Sparkles,
    color: 'bg-purple-500',
    category: 'ai',
    defaultConfig: {},
  },
  {
    type: 'set_variable',
    label: 'Definir variável',
    description: 'Salva valor em variável',
    icon: Variable,
    color: 'bg-teal-500',
    category: 'logic',
    defaultConfig: { name: '', value: '' },
  },
  {
    type: 'notify_user',
    label: 'Notificar',
    description: 'Cria notificação interna',
    icon: Bell,
    color: 'bg-rose-500',
    category: 'action',
    defaultConfig: { title: '', message: '' },
  },
  {
    type: 'start_flow',
    label: 'Iniciar sub-fluxo',
    description: 'Executa outro fluxo',
    icon: PlayCircle,
    color: 'bg-indigo-500',
    category: 'flow',
    defaultConfig: { flow_id: '', variables: {} },
  },
  {
    type: 'end',
    label: 'Fim',
    description: 'Encerra o fluxo',
    icon: Flag,
    color: 'bg-zinc-500',
    category: 'flow',
    defaultConfig: {},
  },
]

export function getNodeMeta(type: string): NodeCatalogEntry | null {
  return NODE_CATALOG.find((n) => n.type === type) ?? null
}
